### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by synle** [synle/har-visual-native#4]
### TODO
- [x] persist the historical stuffs on file - #3 and #4
- [x] attempt to load the content from the historical entry on disk if the file is no longer there - via revision - #3 
- [ ] Add button to Delete revision 
- [ ] Add button to Delete recent har entry
- [ ] Fix up the build pipeline
- [ ] More advanced viewing of other mime types
- [x] Hook up MUI for better UI - #7
- [ ] Hook up better grid library for filtering
- [ ] Generate curl calls
- [ ] Generate fetch calls
- [ ] Add button to extract HAR.
